[build]
publish = "public"
command = "npm run build"
functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

  from = "/*"
  to = "/"
  status = 302
  force = true # COMMENT: ensure that we always redirect

